### model
model_name_or_path: THUDM/chatglm3-6b
# quantization_bit: 4

### method
stage: sft
do_train: true
# finetuning_type: lora
lora_target: query_key_value

### dataset
dataset: zeroshot/twitter-financial-news-sentiment
cutoff_len: 512
jsonl_path: data/tfns_dataset.jsonl
save_path: data/tfns_dataset

### output
output_dir: saves/chatglm3-7b/lora/sft
logging_steps: 10
save_steps: 500
# plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 0.0001
num_train_epochs: 2
# lr_scheduler_type: cosine
warmup_steps: 1000
# fp16: true

### eval
val_size: 0.2
# per_device_eval_batch_size: 1
evaluation_strategy: steps
# eval_steps: 500